### ISSUE TITLE
Symfony Deprecation

### ISSUE THREAD

**Issue by chrisnoden** [somnambulist-tech/api-client#1]
In `src/Client/EventListeners/InjectHeadersFromRequestStack.php line 36`

> Since symfony/http-foundation 5.3: "Symfony\Component\HttpFoundation\RequestStack::getMasterRequest()" is deprecated, use "getMainRequest()" instead.

**Comment by dave-redfern** [comment]
Unfortunately this deprecation means introducing a BC break with SF <5.3.

**Comment by dave-redfern** [comment]
3.2.0 removes the deprecation.
